version: '3.8'

services:
  server:
    build:
      context: ./server
    container_name: lang-portal-server-dev
    ports:
      - "8003:8003"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: lang-portal-client-dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8003/api
    depends_on:
      - server
    restart: unless-stopped

networks:
  default:
    name: lang-portal-network-dev 