version: '3.8'

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: lang-portal-api-prod
    ports:
      - "8003:8003"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: lang-portal-client-prod
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - api

networks:
  default:
    name: lang-portal-network