version: '3.8'

services:
  api:
    build:
      context: .
    container_name: lang-portal-api
    ports:
      - "8003:8003"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/client/node_modules
      - /app/server/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: lang-portal-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    depends_on:
      - api

networks:
  default:
    name: lang-portal-network