version: '3.8'

services:
  tts-service:
    image: ghcr.io/coqui-ai/tts:latest
    container_name: tts-microservice
    ports:
      - "5002:5002"
    volumes:
      - ./models:/root/.local/share/tts
    environment:
      - MODEL_NAME=tts_models/en/ljspeech/tacotron2-DDC
    command: ["--model_name", "tts_models/en/ljspeech/tacotron2-DDC"]
    restart: unless-stopped

networks:
  default:
    driver: bridge
